// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUuG__4kedZsxe_RAyxHmqQh2hhVlEUfU',
    appId: '1:1081804346757:web:fa8ae7f9ab9e6031f220ec',
    messagingSenderId: '1081804346757',
    projectId: 'police-complaint-d8b4a',
    authDomain: 'police-complaint-d8b4a.firebaseapp.com',
    storageBucket: 'police-complaint-d8b4a.appspot.com',
    measurementId: 'G-ET1EF635E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr4F1u3dUJMUFHrnKMfQz00JBKF-pA81s',
    appId: '1:1081804346757:android:23b0a70c872d2100f220ec',
    messagingSenderId: '1081804346757',
    projectId: 'police-complaint-d8b4a',
    storageBucket: 'police-complaint-d8b4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4CwMl8S-ZEj0wvAlrYVOI0BQ6zdwSckA',
    appId: '1:1081804346757:ios:3a33b0241f34f812f220ec',
    messagingSenderId: '1081804346757',
    projectId: 'police-complaint-d8b4a',
    storageBucket: 'police-complaint-d8b4a.appspot.com',
    iosClientId: '1081804346757-90s7dame6acjeu4hnsdru5hh64u2306m.apps.googleusercontent.com',
    iosBundleId: 'com.example.policecomplaintweb.policeComplaintWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4CwMl8S-ZEj0wvAlrYVOI0BQ6zdwSckA',
    appId: '1:1081804346757:ios:3a33b0241f34f812f220ec',
    messagingSenderId: '1081804346757',
    projectId: 'police-complaint-d8b4a',
    storageBucket: 'police-complaint-d8b4a.appspot.com',
    iosClientId: '1081804346757-90s7dame6acjeu4hnsdru5hh64u2306m.apps.googleusercontent.com',
    iosBundleId: 'com.example.policecomplaintweb.policeComplaintWeb',
  );
}
